
[settings]
experimental = true
idiomatic_version_file_enable_tools = []

[tools]
awscli = "latest"
bun = "latest"
gh = "latest"
go = "latest"
mc = "latest"
node = "latest"
rust = "latest"
just = "latest"
mongosh = "latest"
ty = "latest"
ruff = "latest"
prek = "latest"
actionlint = "latest"
"github:alltuner/mise-completions-sync" = "latest"
